export const tabs = [
  {
    id: "87152385",
    name: "About the user object",
    isChildren: false,
    slug: "about-the-user-object",
  },
  {
    id: "12345",
    name: "Integrations",
    slug: "integrations",
    isChildren: false,
  },
  {
    id: "12346",
    icon: "https://supertokens.com/img/logos/next-logo.png",
    name: "Nextjs",
    slug: "nextjs",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12347",
    name: "Using the app directory",
    slug: "using-the-app-directory",
    isChildren: true,
    parentId: "12346",
  },
  {
    id: "12348",
    name: "About",
    slug: "about",
    isChildren: true,
    parentId: "12347",
  },
  {
    id: "12349",
    name: "Configuration",
    slug: "configuration",
    isChildren: true,
    parentId: "12347",
  },
  {
    id: "12350",
    name: "Showing the Login UI",
    slug: "showing-the-login-ui",
    isChildren: true,
    parentId: "12347",
  },
  {
    id: "12351",
    name: "Checking for sessions in frontend routes",
    slug: "checking-for-sessions-in-frontend-routes",
    isChildren: true,
    parentId: "12347",
  },
  {
    id: "12352",
    name: "Checking for sessions in API routes",
    slug: "checking-for-sessions-in-api-routes",
    isChildren: true,
    parentId: "12347",
  },
  {
    id: "12353",
    name: "Adding a session guard to each API route",
    slug: "adding-a-session-guard-to-each-api-route",
    isChildren: true,
    parentId: "12352",
  },
  {
    id: "12354",
    name: "Using the NextJs Middleware",
    slug: "using-the-nextjs-middleware",
    isChildren: true,
    parentId: "12352",
  },
  {
    id: "12355",
    name: "Using the pages directory",
    slug: "using-the-pages-directory",
    isChildren: true,
    parentId: "12346",
  },
  {
    id: "12356",
    name: "About",
    slug: "about",
    isChildren: true,
    parentId: "12355",
  },
  {
    id: "12357",
    name: "Configuration",
    slug: "configuration",
    isChildren: true,
    parentId: "12355",
  },
  {
    id: "12358",
    name: "Showing the Login UI",
    slug: "showing-the-login-ui",
    isChildren: true,
    parentId: "12355",
  },
  {
    id: "12359",
    name: "Adding auth APIs",
    slug: "adding-auth-apis",
    isChildren: true,
    parentId: "12355",
  },
  {
    id: "12360",
    name: "Session verification",
    slug: "session-verification",
    isChildren: true,
    parentId: "12355",
  },
  {
    id: "12361",
    name: "Session verification in an API call",
    slug: "session-verification-in-an-api-call",
    isChildren: true,
    parentId: "12360",
  },
  {
    id: "12362",
    name: "Session verification in getServerSideprops",
    slug: "session-verification-in-getserversideprops",
    isChildren: true,
    parentId: "12360",
  },
  {
    id: "12363",
    icon: "https://supertokens.com/img/logos/hasura-logo.png",
    name: "Hasura",
    slug: "hasura",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12364",
    name: "Authentication using JWTs",
    slug: "authentication-using-jwts",
    isChildren: true,
    parentId: "12363",
  },
  {
    id: "12365",
    name: "GraphQl",
    icon: "https://supertokens.com/img/logos/graphql-logo.png",
    slug: "graphql",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12366",
    name: "Backend setup",
    slug: "backend-setup",
    isChildren: true,
    parentId: "12365",
  },
  {
    id: "12367",
    name: "Making request from the frontend",
    slug: "making-request-from-the-frontend",
    isChildren: true,
    parentId: "12365",
  },
  {
    id: "12368",
    name: "NestJs",
    icon: "https://supertokens.com/img/logos/nest-logo.svg",
    slug: "nestjs",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12369",
    name: "Guide",
    slug: "guide",
    isChildren: true,
    parentId: "12368",
  },
  {
    id: "12370",
    icon: "https://supertokens.com/img/logos/supabase-logo.jpg",
    name: "Supabase",
    slug: "supabase",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12371",
    name: "About",
    slug: "about",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12372",
    name: "Supabase Setup",
    slug: "supabase-setup",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12373",
    name: "Supabase JWT creation",
    slug: "supabase-jwt-creation",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12374",
    name: "Creating a Supabase client",
    slug: "creating-a-supabase-client",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12375",
    name: "Inserting users into Supabase when they sign up",
    slug: "inserting-users-into-supabase-when-they-sign-up",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12376",
    name: "Retrieve the user's email on the frontend",
    slug: "retrieve-the-users-email-on-the-frontend",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12377",
    name: "Create Policies to enforce Row Level Security",
    slug: "create-policies-to-enforce-row-level-security",
    isChildren: true,
    parentId: "12370",
  },
  {
    id: "12378",
    icon: "https://supertokens.com/img/logos/vercel.jpeg",
    name: "Vercel",
    slug: "vercel",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12379",
    name: "About",
    slug: "about",
    isChildren: true,
    parentId: "12378",
  },
  {
    id: "12380",
    icon: "https://supertokens.com/img/logos/netlify.svg",
    name: "Netlify",
    slug: "netlify",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12097838009",
    icon: "https://supertokens.com/img/logos/aws-lambda.svg",
    name: "AWS Lambda",
    slug: "aws-lambda",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12090907009",
    icon: "https://supertokens.com/img/logos/capacitorjs-icon.svg",
    name: "Capacitor",
    slug: "capacitor",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12812709",
    icon: "https://supertokens.com/img/logos/t4-app.png",
    name: "T4 App",
    slug: "t4-app",
    isChildren: true,
    parentId: "12345",
  },
  {
    id: "12381",
    name: "Frontend Setup",
    slug: "frontend-setup",
    isChildren: true,
    parentId: "12380",
  },
  {
    id: "12382",
    name: "Backend Setup",
    slug: "backend-setup",
    isChildren: true,
    parentId: "12380",
  },
  {
    id: "12383",
    name: "Exposing Auth APIs",
    slug: "exposing-auth-apis",
    isChildren: true,
    parentId: "12380",
  },
  {
    id: "12384",
    name: "Session verification/ Building your APIs",
    slug: "session-verification-building-your-apis",
    isChildren: true,
    parentId: "12380",
  },
  {
    id: "12385",
    name: "Next steps",
    slug: "next-steps",
    isChildren: true,
    parentId: "12380",
  },
  {
    id: "12386",
    name: "Session management",
    slug: "session-management",
    isChildren: false,
  },
  {
    id: "12387",
    name: "How it works",
    slug: "how-it-works",
    isChildren: true,
    parentId: "12386",
  },
  {
    id: "12388",
    name: "Protecting API routes",
    slug: "protecting-api-routes",
    isChildren: true,
    parentId: "12386",
  },
  {
    id: "12389",
    name: "Overview",
    slug: "overview",
    isChildren: true,
    parentId: "12388",
  },
  {
    id: "12390",
    name: "Using the verifySession middleware",
    slug: "using-the-verifysession-middleware",
    isChildren: true,
    parentId: "12388",
  },
  {
    id: "12391",
    name: "Using the getSession function",
    slug: "using-the-getsession-function",
    isChildren: true,
    parentId: "12388",
  },
  {
    id: "12392",
    name: "Manually verify the JWT",
    slug: "manually-verify-the-jwt",
    isChildren: true,
    parentId: "12388",
  },
  {
    id: "12393",
    name: "Protecting frontend routes",
    slug: "protecting-frontend-routes",
    isChildren: true,
    parentId: "12386",
  },
  {
    id: "12394",
    name: "Auth flow customization",
    slug: "auth-flow-customization",
    isChildren: false,
  },
  {
    id: "123909",
    name: "Post signin / signup callbacks",
    slug: "post-signin-signup-callbacks",
    isChildren: true,
    parentId: "12394",
  },
  {
    id: "123909",
    name: "Sign in / up",
    slug: "sign-in-up",
    isChildren: true,
    parentId: "12394",
  },
  {
    id: "12395",
    name: "Additional features",
    slug: "additional-features",
    isChildren: false,
  },
  {
    id: "12398755",
    name: "User roles",
    slug: "user-roles",
    isChildren: true,
    parentId: "12395",
  },
  {
    id: "12396",
    name: "Rate limit policy",
    slug: "rate-limit-policy",
    isChildren: false,
  },
  {
    id: "12397",
    name: "Testing and debugging",
    slug: "testing-and-debugging",
    isChildren: false,
  },
  {
    id: "1962397",
    name: "Testing with postman",
    slug: "testing-with-postman",
    isChildren: true,
    parentId: "12397",
  },
  {
    id: "1139862397",
    name: "How to enable debug logs",
    slug: "how-to-enable-debug-logs",
    isChildren: true,
    parentId: "12397",
  },
  {
    id: "12340997",
    name: "CORS issue",
    slug: "cors-issue",
    isChildren: true,
    parentId: "12397",
  },
  {
    id: "12398",
    name: "Migration",
    slug: "migration",
    isChildren: false,
  },
  {
    id: "1239098",
    name: "About",
    slug: "about",
    isChildren: true,
    parentId: "12398",
  },
  {
    id: "12399",
    name: "References",
    slug: "references",
    isChildren: false,
  },
  {
    id: "1002399",
    name: "How SuperTokens works",
    slug: "how-super-tokens-works",
    isChildren: true,
    parentId: "12399",
  },
];

Object.freeze(tabs);
